import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const seedHeritageSites = mutation({
  args: {},
  handler: async (ctx, args) => {
    // Get the first user or use a system user ID
    const users = await ctx.db.query("users").collect();
    const userId = users.length > 0 ? users[0]._id : await ctx.db.insert("users", {
      email: "system@virasat.com",
      role: "admin",
    });
    
    const sites = [
      {
        name: "Taj Mahal",
        description: "An ivory-white marble mausoleum on the right bank of the river Yamuna, commissioned by Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal.",
        historicalSignificance: "Built between 1632-1653, it represents the pinnacle of Mughal architecture and is considered one of the finest examples of Indo-Islamic art.",
        category: "monument" as const,
        state: "Uttar Pradesh",
        city: "Agra",
        latitude: 27.1751,
        longitude: 78.0421,
        isUNESCO: true,
        timePeriod: "17th Century (1632-1653)",
        visitorGuidelines: "Open from sunrise to sunset except Fridays. Photography allowed but no tripods inside the main mausoleum.",
        folkTales: "Legend says that Shah Jahan planned to build a black marble replica across the river but was imprisoned by his son before he could realize this dream.",
        culturalHeritage: "The Taj Mahal embodies Mughal garden design, Persian calligraphy, and intricate pietra dura inlay work. It represents the synthesis of Islamic, Persian, and Indian architectural traditions.",
        cuisine: "Agra is famous for Petha (sweet made from ash gourd), Mughlai cuisine including biryani, kebabs, and the rich Agra ka Petha.",
        stories: "The monument took 22 years and 20,000 artisans to complete. Master craftsmen were brought from Persia, Turkey, and Europe. Some say Shah Jahan cut off the hands of workers to prevent them from replicating the design.",
        community: "The local community includes descendants of the original craftsmen who still practice traditional marble inlay work. The area hosts annual Taj Mahotsav celebrating local arts and crafts.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Hampi",
        description: "Ancient village and UNESCO World Heritage Site with magnificent ruins of the Vijayanagara Empire, featuring over 1,600 monuments spread across 4,100 hectares.",
        historicalSignificance: "Capital of the Vijayanagara Empire (1336-1565), once one of the richest cities in the world, known for its grand architecture and prosperous trade.",
        category: "archaeological" as const,
        state: "Karnataka",
        city: "Hampi",
        latitude: 15.3350,
        longitude: 76.4600,
        isUNESCO: true,
        timePeriod: "14th-16th Century",
        visitorGuidelines: "Best visited between October-February. Wear comfortable shoes for walking. Respect religious sites and dress modestly.",
        folkTales: "According to Ramayana, Hampi is believed to be Kishkindha, the monkey kingdom ruled by Vali and Sugriva. The boulders are said to be remnants of the bridge to Lanka.",
        culturalHeritage: "Hampi showcases Dravidian architecture with intricate stone carvings, massive gopurams, and the famous Stone Chariot. The site hosts the annual Hampi Utsav celebrating classical dance and music.",
        cuisine: "Local specialties include Jolada Rotti (sorghum flatbread), Badanekai Yennegai (stuffed brinjal), and traditional Karnataka thali with Bisi Bele Bath.",
        stories: "The empire fell after the Battle of Talikota in 1565. Legend says the city was so wealthy that merchants sold diamonds and pearls in the streets. The Virupaksha Temple has been continuously active for over 1,300 years.",
        community: "The local community includes temple priests, traditional musicians, and artisans. Many families have lived here for generations, maintaining ancient traditions and rituals.",
        view360Url: "https://artsandculture.google.com/story/hampi-monuments/",
        view3dUrl: "https://artsandculture.google.com/asset/vitthala-temple-hampi/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Khajuraho Temples",
        description: "Group of Hindu and Jain temples famous for their nagara-style architectural symbolism and erotic sculptures, representing the finest examples of medieval Indian art.",
        historicalSignificance: "Built by Chandela dynasty between 950-1050 CE, only 25 of the original 85 temples survive today, showcasing the zenith of temple architecture in Central India.",
        category: "temple" as const,
        state: "Madhya Pradesh",
        city: "Khajuraho",
        latitude: 24.8318,
        longitude: 79.9199,
        isUNESCO: true,
        timePeriod: "10th-11th Century",
        visitorGuidelines: "Open daily. Light and sound show in the evening. Photography allowed with ticket. Dress respectfully.",
        folkTales: "Legend says the temples were built by Hemavati, a beautiful Brahmin priest's daughter who was seduced by the moon god. Her son Chandravarman founded the Chandela dynasty and built these temples.",
        culturalHeritage: "The temples represent Tantric traditions and celebrate all aspects of life - spiritual, material, and sensual. The annual Khajuraho Dance Festival showcases classical Indian dance forms against the temple backdrop.",
        cuisine: "Local delicacies include Bhutte ka Kees (grated corn dish), Poha-Jalebi, Mawa-Bati, and traditional Bundelkhandi cuisine.",
        stories: "Only 10% of the sculptures are erotic; the rest depict gods, goddesses, warriors, musicians, and everyday life. The temples were 'rediscovered' by British engineer T.S. Burt in 1838, hidden by dense forests.",
        community: "Local artisans continue the tradition of stone carving. The community celebrates Mahashivratri with great fervor, and traditional dance forms are passed down through generations.",
        view360Url: "https://artsandculture.google.com/story/khajuraho-temples/",
        view3dUrl: "https://artsandculture.google.com/asset/kandariya-mahadeva-temple/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Konark Sun Temple",
        description: "13th-century Sun Temple designed as a gigantic chariot with elaborately carved stone wheels, pillars, and walls, dedicated to the Hindu sun god Surya.",
        historicalSignificance: "Built by King Narasimhadeva I of the Eastern Ganga Dynasty around 1250 CE, it represents the pinnacle of Kalinga architecture and was once called the 'Black Pagoda' by European sailors.",
        category: "temple" as const,
        state: "Odisha",
        city: "Konark",
        latitude: 19.8876,
        longitude: 86.0945,
        isUNESCO: true,
        timePeriod: "13th Century (1250 CE)",
        visitorGuidelines: "Open from sunrise to sunset. Annual Konark Dance Festival in December. Beach nearby for sunset views.",
        folkTales: "Legend says the temple was built in 12 years by 1,200 artisans. The chief architect's son sacrificed himself to complete the temple when a crucial stone wouldn't fit. The magnetic lodestone at the top made ships' compasses malfunction.",
        culturalHeritage: "The temple is designed as Surya's chariot with 24 wheels and 7 horses. Intricate carvings depict the wheel of time, erotic sculptures, and daily life. The Konark Dance Festival celebrates Odissi and other classical dances.",
        cuisine: "Odisha cuisine includes Dalma (lentils with vegetables), Pakhala Bhata (fermented rice), Chhena Poda (cheese dessert), and fresh seafood from nearby coast.",
        stories: "The temple originally had a 229-foot tower that collapsed in the 15th century. The wheels are sundials that accurately tell time. Portuguese sailors called it 'Black Pagoda' as it appeared dark from the sea and caused shipwrecks.",
        community: "Local Gotipua dancers (young boys performing Odissi) maintain ancient traditions. Fishing communities nearby celebrate Magha Saptami with ritual bathing. Stone carvers continue traditional crafts.",
        view360Url: "https://artsandculture.google.com/story/sun-temple-konark/",
        view3dUrl: "https://artsandculture.google.com/asset/sun-temple-konark/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Ajanta Caves",
        description: "Rock-cut Buddhist cave monuments featuring ancient paintings and sculptures, considered masterpieces of Buddhist religious art and universal pictorial art.",
        historicalSignificance: "Created in two phases: 2nd century BCE to 1st century CE, and 5th century CE. Abandoned around 650 CE and rediscovered in 1819 by British officer John Smith.",
        category: "archaeological" as const,
        state: "Maharashtra",
        city: "Aurangabad",
        latitude: 20.5519,
        longitude: 75.7033,
        isUNESCO: true,
        timePeriod: "2nd Century BCE - 6th Century CE",
        visitorGuidelines: "Closed on Mondays. Photography prohibited inside caves. Carry water and wear comfortable shoes. Best lighting in morning hours.",
        folkTales: "Local legend says the caves were created by divine architects overnight. Another tale speaks of a prince who renounced his kingdom and meditated here, inspiring the creation of these sacred spaces.",
        culturalHeritage: "The caves contain some of the finest examples of ancient Indian art, depicting Jataka tales, Buddha's life, and celestial beings. The paintings use natural pigments that have survived 1,500 years.",
        cuisine: "Aurangabad is famous for Naan Khaliya (mutton dish), Tahri (vegetarian biryani), and Sheermal (sweet flatbread). Local street food includes Paan and Irani chai.",
        stories: "Cave 1 contains the famous Padmapani and Vajrapani bodhisattva paintings. The caves were carved from top to bottom, removing 3 million cubic feet of rock. British officer John Smith discovered them while hunting tigers.",
        community: "Local guides are descendants of families who've lived near the caves for generations. Buddhist monks occasionally visit for meditation. The community celebrates Buddha Purnima with special prayers.",
        view360Url: "https://artsandculture.google.com/story/ajanta-caves/",
        view3dUrl: "https://artsandculture.google.com/asset/ajanta-caves/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Mysore Palace",
        description: "Historical palace and royal residence of the Wadiyar dynasty, known for its Indo-Saracenic architecture, intricate carvings, and grand Durbar Hall.",
        historicalSignificance: "The current palace was built between 1897-1912 after the old palace was destroyed by fire. It served as the seat of the Kingdom of Mysore and is now one of India's most visited monuments.",
        category: "palace" as const,
        state: "Karnataka",
        city: "Mysore",
        latitude: 12.3051,
        longitude: 76.6551,
        isUNESCO: false,
        timePeriod: "Early 20th Century (1897-1912)",
        visitorGuidelines: "Open daily. Illuminated on Sundays and public holidays. No photography inside. Audio guides available. Dress modestly.",
        folkTales: "Legend says the city was ruled by the demon Mahishasura, who was slain by Goddess Chamundeshwari. The city's name 'Mysuru' comes from 'Mahishuru' (Mahisha's town).",
        culturalHeritage: "The palace hosts the famous Dasara festival with royal processions, cultural programs, and the illuminated palace. It showcases a blend of Hindu, Muslim, Rajput, and Gothic architectural styles.",
        cuisine: "Mysore is famous for Mysore Pak (sweet), Mysore Masala Dosa, Bisi Bele Bath, and traditional Karnataka meals served on banana leaves.",
        stories: "The palace has 145 rooms and was designed by British architect Henry Irwin. It cost Rs 41.5 lakhs to build. The Durbar Hall's ceiling has paintings by Indian artists. The palace uses 96,000 light bulbs for illumination.",
        community: "The Wadiyar royal family still resides in a portion of the palace. Local artisans maintain traditional crafts like sandalwood carving, silk weaving, and incense making. The community celebrates Dasara with 10 days of festivities.",
        view360Url: "https://artsandculture.google.com/story/mysore-palace/",
        view3dUrl: "https://artsandculture.google.com/asset/mysore-palace/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Qutub Minar",
        description: "73-meter tall victory tower and minaret made of red sandstone and marble, the tallest brick minaret in the world and an outstanding example of Indo-Islamic architecture.",
        historicalSignificance: "Construction began in 1192 by Qutb-ud-din Aibak and was completed by his successor Iltutmish. It marks the beginning of Muslim rule in India and stands on the ruins of Lal Kot.",
        category: "monument" as const,
        state: "Delhi",
        city: "New Delhi",
        latitude: 28.5244,
        longitude: 77.1855,
        isUNESCO: true,
        timePeriod: "12th-13th Century (1192-1220)",
        visitorGuidelines: "Open daily except Mondays. Entry restricted to ground level only. Complex includes Iron Pillar and Quwwat-ul-Islam Mosque.",
        folkTales: "Legend says the tower was named after Qutbuddin Bakhtiar Kaki, a Sufi saint. Another tale claims it was built as a tower of victory to celebrate Muslim dominance over Delhi.",
        culturalHeritage: "The complex showcases early Indo-Islamic architecture with intricate calligraphy, geometric patterns, and verses from the Quran. The Iron Pillar nearby has stood rust-free for 1,600 years.",
        cuisine: "Old Delhi nearby offers Mughlai cuisine, Paranthe Wali Gali, Karim's kebabs, and street food like chaat, chole bhature, and jalebi.",
        stories: "The tower has 379 steps (now closed to public after accidents). It was struck by lightning twice and damaged by earthquakes. The Iron Pillar's rust-resistant composition remains a metallurgical mystery.",
        community: "The area is surrounded by urban Delhi but maintains historical significance. Local historians and archaeologists conduct regular studies. The community celebrates Qutub Festival showcasing classical music and dance.",
        view360Url: "https://artsandculture.google.com/story/qutub-minar/",
        view3dUrl: "https://sketchfab.com/3d-models/qutub-minar-delhi-india/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Meenakshi Temple",
        description: "Historic Hindu temple dedicated to Goddess Meenakshi and Lord Sundareswarar, featuring 14 magnificent gopurams covered with thousands of colorful sculptures.",
        historicalSignificance: "The temple has ancient origins but was rebuilt in the 17th century by Nayak rulers. It's a prime example of Dravidian architecture and has been a center of Tamil culture for millennia.",
        category: "temple" as const,
        state: "Tamil Nadu",
        city: "Madurai",
        latitude: 9.9195,
        longitude: 78.1193,
        isUNESCO: false,
        timePeriod: "17th Century (rebuilt)",
        visitorGuidelines: "Open 5 AM to 12:30 PM and 4 PM to 10 PM. Dress modestly. Remove footwear. Photography restricted in inner sanctum. Witness evening aarti ceremony.",
        folkTales: "Legend says Goddess Parvati performed penance to marry Lord Shiva here. She was born as Meenakshi (fish-eyed goddess) to the Pandyan king and ruled Madurai before marrying Sundareswarar (Shiva).",
        culturalHeritage: "The temple is a living monument with daily rituals, festivals, and classical music performances. The annual Meenakshi Thirukalyanam (celestial wedding) attracts millions. The Hall of Thousand Pillars is an architectural marvel.",
        cuisine: "Madurai is famous for Jigarthanda (cold drink), Paruthi Paal (cottonseed milk), Kari Dosa (mutton dosa), and traditional Tamil meals with Chettinad flavors.",
        stories: "The temple has 33,000 sculptures. The golden lotus tank is said to judge the quality of literary works - good works float while poor ones sink. The temple complex covers 45 acres with 12 gopurams.",
        community: "Temple priests belong to families serving for generations. The community includes traditional musicians, dancers, and flower vendors. Daily rituals involve hundreds of people maintaining ancient traditions.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Hawa Mahal",
        description: "Palace of Winds, a five-story pink sandstone structure with 953 small windows (jharokhas) designed to allow royal ladies to observe street festivals while remaining unseen.",
        historicalSignificance: "Built in 1799 by Maharaja Sawai Pratap Singh, designed by architect Lal Chand Ustad. It's an iconic symbol of Jaipur and represents Rajputana architecture.",
        category: "palace" as const,
        state: "Rajasthan",
        city: "Jaipur",
        latitude: 26.9239,
        longitude: 75.8267,
        isUNESCO: false,
        timePeriod: "18th Century (1799)",
        visitorGuidelines: "Open daily. Best viewed from outside in morning light. Museum inside showcases royal artifacts. Rooftop offers city views.",
        folkTales: "Legend says the palace was built so royal women could watch processions without being seen, following purdah tradition. The honeycomb design was inspired by Lord Krishna's crown.",
        culturalHeritage: "The palace exemplifies Rajput architecture with its unique ventilation system. The pink sandstone matches Jaipur's 'Pink City' theme. It's part of the City Palace complex.",
        cuisine: "Jaipur offers Dal Baati Churma, Ghewar, Pyaaz Kachori, Laal Maas (spicy mutton), and traditional Rajasthani thali with Ker Sangri.",
        stories: "The palace has no stairs, only ramps for easy access. The 953 windows create a natural air conditioning system. It's only one room wide but five stories tall. The facade resembles a honeycomb.",
        community: "Local artisans specialize in block printing, blue pottery, and jewelry making. The community celebrates Teej and Gangaur festivals with processions passing by the palace.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Golden Temple (Harmandir Sahib)",
        description: "The holiest Gurdwara of Sikhism, featuring a stunning gold-plated dome and surrounded by a sacred pool (Amrit Sarovar), symbolizing equality and brotherhood.",
        historicalSignificance: "Foundation laid by Guru Ram Das in 1577, completed by Guru Arjan in 1604. The temple has been destroyed and rebuilt several times, with the current gold plating added by Maharaja Ranjit Singh in 1830.",
        category: "temple" as const,
        state: "Punjab",
        city: "Amritsar",
        latitude: 31.6200,
        longitude: 74.8765,
        isUNESCO: false,
        timePeriod: "16th Century (1577-1604)",
        visitorGuidelines: "Open 24/7. Cover head, remove shoes, wash feet. Free community kitchen (langar) serves 100,000+ daily. Photography allowed. Dress modestly.",
        folkTales: "Legend says the site was a meditation spot for Buddha. The pool's water is believed to have healing properties. The temple has four entrances symbolizing openness to all religions and castes.",
        culturalHeritage: "The temple represents Sikh values of equality, service, and devotion. The langar (free kitchen) serves everyone regardless of religion, caste, or status. Continuous recitation of Guru Granth Sahib occurs 24/7.",
        cuisine: "Amritsar is famous for Amritsari Kulcha, Chole, Lassi, Makki di Roti with Sarson da Saag, and the legendary langar meals served at the temple.",
        stories: "The temple is built lower than ground level, symbolizing humility. 750 kg of gold was used in plating. The langar uses 12,000 kg of flour daily. The temple survived Operation Blue Star in 1984.",
        community: "Volunteers (sewadars) from around the world serve in the langar. The community maintains the tradition of kar seva (voluntary service). Nagar Kirtan processions celebrate Sikh festivals.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Ellora Caves",
        description: "Rock-cut cave complex featuring Buddhist, Hindu, and Jain monuments, with the magnificent Kailasa temple carved from a single rock, representing religious harmony.",
        historicalSignificance: "Created between 600-1000 CE by different dynasties. Cave 16 (Kailasa temple) is the largest monolithic structure in the world, carved top-down from a single rock.",
        category: "archaeological" as const,
        state: "Maharashtra",
        city: "Aurangabad",
        latitude: 20.0269,
        longitude: 75.1793,
        isUNESCO: true,
        timePeriod: "6th-10th Century CE",
        visitorGuidelines: "Closed on Tuesdays. Best visited in morning. Wear comfortable shoes. Carry water. Photography allowed. Caves 1-12 Buddhist, 13-29 Hindu, 30-34 Jain.",
        folkTales: "Legend says the Kailasa temple was built in a week by divine architects. Another tale speaks of a queen who prayed for her husband's recovery and vowed to build a temple, which was completed miraculously fast.",
        culturalHeritage: "The caves showcase religious tolerance with Buddhist, Hindu, and Jain monuments coexisting. The Kailasa temple represents Mount Kailash, Shiva's abode. Intricate carvings depict mythology and daily life.",
        cuisine: "Aurangabad offers Naan Khaliya, Tahri, Sheermal, and Himroo textiles. Local sweets include Jalebi and traditional Maharashtrian cuisine.",
        stories: "The Kailasa temple required removal of 200,000 tons of rock. It took 100 years and multiple generations to complete. The caves were carved using only hammers and chisels. Cave 10 has excellent acoustics.",
        community: "Local guides belong to families with generations of knowledge. Buddhist monks visit for meditation. The community celebrates festivals from all three religions represented in the caves.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Amer Fort",
        description: "Majestic fort palace built with red sandstone and marble, featuring artistic Hindu elements, large ramparts, series of gates, and cobbled paths overlooking Maota Lake.",
        historicalSignificance: "Built by Raja Man Singh I in 1592, expanded by successive rulers. It served as the main residence of Rajput Maharajas and their families for centuries before Jaipur city was established.",
        category: "fort" as const,
        state: "Rajasthan",
        city: "Jaipur",
        latitude: 26.9855,
        longitude: 75.8513,
        isUNESCO: true,
        timePeriod: "16th Century (1592)",
        visitorGuidelines: "Open daily. Elephant rides available in morning. Light and sound show in evening. Photography allowed. Wear comfortable shoes for climbing.",
        folkTales: "Legend says a hidden treasure lies beneath the fort. The Sheesh Mahal (Mirror Palace) is said to light up with just a single candle's reflection. Secret passages connected the fort to Jaigarh Fort.",
        culturalHeritage: "The fort showcases Rajput architecture with Mughal influences. The Sheesh Mahal has thousands of mirror pieces. The Diwan-i-Khas features intricate marble work. Annual festivals celebrate Rajasthani culture.",
        cuisine: "Local specialties include Dal Baati Churma, Laal Maas, Ghewar, Pyaaz Kachori, and traditional Rajasthani thali with Ker Sangri and Gatte ki Sabzi.",
        stories: "The fort has four courtyards and several gates. The Ganesh Pol gate has beautiful frescoes. A secret tunnel connects to Jaigarh Fort. The fort required 5,000 workers and took 25 years to build.",
        community: "Local communities include descendants of royal servants, traditional musicians, and artisans. Elephant caretakers maintain centuries-old traditions. The community celebrates Teej and Gangaur with royal processions.",
        view360Url: "https://artsandculture.google.com/story/amer-fort/",
        view3dUrl: "https://artsandculture.google.com/asset/amer-fort/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Victoria Memorial",
        description: "Grand marble building dedicated to Queen Victoria, combining British and Mughal architecture, now a museum housing colonial-era artifacts and paintings.",
        historicalSignificance: "Built between 1906-1921 by Lord Curzon after Queen Victoria's death. Designed by William Emerson, it represents the British Raj's architectural legacy in India.",
        category: "monument" as const,
        state: "West Bengal",
        city: "Kolkata",
        latitude: 22.5448,
        longitude: 88.3426,
        isUNESCO: false,
        timePeriod: "Early 20th Century (1906-1921)",
        visitorGuidelines: "Closed on Mondays. Museum inside showcases British Raj history. Beautiful gardens for evening walks. Light and sound show available.",
        folkTales: "Local stories speak of the memorial being haunted by British ghosts. The Angel of Victory statue on top rotates with the wind, symbolizing changing times.",
        culturalHeritage: "The memorial blends Indo-Saracenic architecture with Mughal and British elements. It houses rare paintings, manuscripts, and artifacts from the colonial period. The gardens host cultural events.",
        cuisine: "Kolkata is famous for Rosogolla, Mishti Doi, Kathi Rolls, Puchka (pani puri), Fish Curry, and Bengali sweets from nearby shops.",
        stories: "The memorial used 3 million cubic feet of white Makrana marble. The Angel of Victory weighs 3 tons. The building cost Rs 1.05 crore, funded by donations. It has 25 galleries and royal halls.",
        community: "The area is a cultural hub with artists, photographers, and historians. The community celebrates Durga Puja with grand pandals nearby. Street vendors sell traditional Bengali snacks.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Sanchi Stupa",
        description: "Ancient Buddhist complex with hemispherical brick structure containing relics of Buddha, featuring ornate gateways (toranas) with intricate carvings depicting Jataka tales.",
        historicalSignificance: "Built by Emperor Ashoka in 3rd century BCE, it's one of the oldest stone structures in India. The Great Stupa was expanded and decorated over centuries, becoming a major Buddhist pilgrimage site.",
        category: "monument" as const,
        state: "Madhya Pradesh",
        city: "Sanchi",
        latitude: 23.4793,
        longitude: 77.7398,
        isUNESCO: true,
        timePeriod: "3rd Century BCE",
        visitorGuidelines: "Open daily. Best visited in morning or evening. Museum nearby. Photography allowed. Peaceful environment for meditation.",
        folkTales: "Legend says Emperor Ashoka built 84,000 stupas across his empire, with Sanchi being among the most important. His wife Devi, from nearby Vidisha, influenced his conversion to Buddhism.",
        culturalHeritage: "The stupa represents Buddha's presence and teachings. The four toranas depict Jataka tales and Buddha's life without showing him directly. The site showcases evolution of Buddhist art and architecture.",
        cuisine: "Local cuisine includes Poha-Jalebi, Bhutte ka Kees, Dal Bafla, and traditional Malwa region dishes. Nearby Bhopal offers Bhopali Gosht Korma and Biryani.",
        stories: "The stupa was abandoned after Buddhism declined in India and was rediscovered in 1818. The four gateways were added in 1st century BCE. The site contains relics of Buddha's disciples Sariputta and Mahamoggallana.",
        community: "Buddhist monks and scholars visit for study and meditation. Local communities maintain the site and celebrate Buddha Purnima. The area has a peaceful, spiritual atmosphere.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Charminar",
        description: "Iconic monument and mosque with four grand arches and minarets, built in Indo-Islamic architecture, symbolizing Hyderabad city and its rich cultural heritage.",
        historicalSignificance: "Built in 1591 by Muhammad Quli Qutb Shah to commemorate the end of a deadly plague. It marks the center of Hyderabad and represents the city's founding.",
        category: "monument" as const,
        state: "Telangana",
        city: "Hyderabad",
        latitude: 17.3616,
        longitude: 78.4747,
        isUNESCO: false,
        timePeriod: "16th Century (1591)",
        visitorGuidelines: "Open daily. Climb 149 steps for city views. Mosque on top floor. Surrounded by bustling bazaars. Best visited in evening. Photography allowed.",
        folkTales: "Legend says the monument was built where the Sultan first met his beloved Bhagmati (later Hyder Mahal). Another tale claims a secret tunnel connects it to Golconda Fort.",
        culturalHeritage: "The monument represents Hyderabad's Qutb Shahi heritage. The surrounding area is famous for pearls, bangles, and traditional crafts. The Laad Bazaar nearby is centuries old.",
        cuisine: "Hyderabad is famous for Hyderabadi Biryani, Haleem, Irani Chai, Osmania Biscuits, Double ka Meetha, and Qubani ka Meetha.",
        stories: "The structure has 45 prayer spaces and a mosque on the top floor. Each minaret is 48.7 meters tall. The monument has a water supply system with Persian wheel. It's built on a single foundation.",
        community: "The area is a vibrant commercial hub with pearl traders, bangle sellers, and traditional craftsmen. The community celebrates Ramadan with special fervor. Old City culture thrives around Charminar.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Jaisalmer Fort",
        description: "Living fort built from yellow sandstone, appearing golden in sunlight, one of the few forts where people still live, featuring palaces, temples, and havelis.",
        historicalSignificance: "Built in 1156 by Rajput ruler Rawal Jaisal, it's one of the largest forts in the world. Unlike most forts, it's a living fort with about 3,000 residents still living inside.",
        category: "fort" as const,
        state: "Rajasthan",
        city: "Jaisalmer",
        latitude: 26.9157,
        longitude: 70.9083,
        isUNESCO: true,
        timePeriod: "12th Century (1156)",
        visitorGuidelines: "Open daily. Explore narrow lanes, shops, and restaurants inside. Sunset views spectacular. Camel safari available. Respect residents' privacy.",
        folkTales: "Legend says the fort was built on Trikuta Hill as prophesied by Lord Krishna. Stories tell of royal women performing jauhar (self-immolation) during sieges. Hidden treasures are said to lie beneath.",
        culturalHeritage: "The fort showcases Rajput architecture with intricate carvings. Jain temples inside have ancient manuscripts. The fort hosts Desert Festival celebrating Rajasthani culture with folk music and dance.",
        cuisine: "Jaisalmer offers Dal Baati Churma, Ker Sangri, Gatte ki Sabzi, Pyaaz Kachori, and unique desert cuisine. Rooftop restaurants serve traditional Rajasthani thalis.",
        stories: "The fort has 99 bastions, 92 built between 1633-1647. It's called 'Sonar Quila' (Golden Fort). The fort has survived three major battles. Intricate havelis inside showcase merchant wealth.",
        community: "Brahmin and Rajput families have lived here for generations. Traditional musicians, craftsmen, and shopkeepers maintain old customs. The community celebrates Gangaur and Teej festivals.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Mahabodhi Temple",
        description: "Sacred Buddhist temple marking the spot where Buddha attained enlightenment under the Bodhi tree, featuring a 50-meter tall pyramidal spire and ancient Bodhi tree descendant.",
        historicalSignificance: "Built by Emperor Ashoka in 3rd century BCE, rebuilt in 5th-6th century CE. It's the most sacred site in Buddhism, where Siddhartha Gautama became Buddha around 500 BCE.",
        category: "temple" as const,
        state: "Bihar",
        city: "Bodh Gaya",
        latitude: 24.6961,
        longitude: 84.9911,
        isUNESCO: true,
        timePeriod: "3rd Century BCE (original), 5th-6th Century CE (current)",
        visitorGuidelines: "Open daily. Dress modestly. Remove shoes. Meditation sessions available. Photography allowed outside. Peaceful atmosphere maintained.",
        folkTales: "Legend says Siddhartha meditated for 49 days under the Bodhi tree, resisting Mara's temptations before attaining enlightenment. The tree is said to be a direct descendant of the original.",
        culturalHeritage: "The temple is a pilgrimage site for Buddhists worldwide. The Bodhi tree is worshipped by devotees. The site hosts Vesak celebrations and meditation retreats. Monasteries from various countries surround the temple.",
        cuisine: "Bodh Gaya offers vegetarian Buddhist cuisine, Tibetan momos, thukpa, and traditional Bihari dishes like Litti Chokha, Sattu Paratha, and Khaja.",
        stories: "The temple's architecture influenced Buddhist temples across Asia. The Bodhi tree has been destroyed and replanted several times. The diamond throne (Vajrasana) marks Buddha's meditation spot. The temple has 1,000+ votive stupas.",
        community: "Buddhist monks from around the world reside here. Local communities support pilgrims and maintain the site. The area has Tibetan, Thai, Japanese, and other international Buddhist communities.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Brihadeeswarar Temple",
        description: "Magnificent Chola temple dedicated to Lord Shiva, featuring a 66-meter tall vimana (tower), massive Nandi statue, and exemplary Dravidian architecture.",
        historicalSignificance: "Built by Raja Raja Chola I in 1010 CE, it represents the zenith of Chola architecture. The temple was built in just 5 years and showcases advanced engineering and artistic excellence.",
        category: "temple" as const,
        state: "Tamil Nadu",
        city: "Thanjavur",
        latitude: 10.7825,
        longitude: 79.1313,
        isUNESCO: true,
        timePeriod: "11th Century (1010 CE)",
        visitorGuidelines: "Open daily. Dress modestly. Remove footwear. Photography allowed outside. Witness daily rituals and poojas. Best visited in morning.",
        folkTales: "Legend says the temple's shadow never falls on the ground at noon. The capstone weighing 80 tons was lifted using a 6 km ramp. The temple is said to be built without any binding material.",
        culturalHeritage: "The temple showcases Chola bronze sculptures, frescoes, and inscriptions. It's a living temple with daily rituals. The annual Brahmotsavam festival attracts thousands. Classical Bharatanatyam performances held regularly.",
        cuisine: "Thanjavur offers traditional Tamil cuisine including Thanjavur Thali, Puliyodarai (tamarind rice), Vadai, and famous Thanjavur Art Plate meals.",
        stories: "The temple has the world's tallest vimana at 66 meters. The Nandi statue is carved from a single rock weighing 25 tons. The temple has 108 dance poses carved on walls. It survived multiple invasions intact.",
        community: "Temple priests belong to families serving for over 1,000 years. The community includes traditional musicians, dancers, and artisans. Thanjavur is known for classical music and art.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Red Fort",
        description: "Massive red sandstone fort complex that served as the main residence of Mughal emperors, featuring palaces, gardens, and the iconic Lahori Gate.",
        historicalSignificance: "Built by Shah Jahan between 1638-1648 when he shifted the capital from Agra to Delhi. It remained the Mughal seat of power until 1857 and witnessed India's independence in 1947.",
        category: "fort" as const,
        state: "Delhi",
        city: "New Delhi",
        latitude: 28.6562,
        longitude: 77.2410,
        isUNESCO: true,
        timePeriod: "17th Century (1638-1648)",
        visitorGuidelines: "Closed on Mondays. Light and sound show in evening. Prime Minister's Independence Day speech from ramparts. Photography allowed. Large complex requires 2-3 hours.",
        folkTales: "Legend says the Kohinoor diamond was once part of the Peacock Throne here. Stories tell of secret tunnels connecting to other Delhi monuments. The fort is said to have underground chambers with treasures.",
        culturalHeritage: "The fort represents Mughal architectural grandeur with Persian influences. The Diwan-i-Khas had the famous Peacock Throne. It's the site of India's Independence Day celebrations annually.",
        cuisine: "Old Delhi nearby offers Mughlai cuisine, Paranthe Wali Gali, Karim's kebabs, Jalebi, and famous street food like chaat and chole bhature.",
        stories: "The fort covers 254 acres with 2.4 km of walls. The Diwan-i-Khas inscription reads 'If there is paradise on earth, it is this, it is this, it is this.' The British looted the fort after 1857 rebellion.",
        community: "The area is surrounded by Old Delhi's vibrant markets. The community celebrates Independence Day with patriotic fervor. Local historians and guides share stories of Mughal glory.",
        view360Url: "https://artsandculture.google.com/story/red-fort-delhi/",
        view3dUrl: "https://artsandculture.google.com/asset/red-fort/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Gol Gumbaz",
        description: "Mausoleum of Sultan Mohammed Adil Shah featuring the world's second-largest dome, famous for its whispering gallery where sounds echo seven times.",
        historicalSignificance: "Built in 1656, it's the largest dome in India and second largest in the world after St. Peter's Basilica. It represents the architectural zenith of the Adil Shahi dynasty.",
        category: "monument" as const,
        state: "Karnataka",
        city: "Bijapur",
        latitude: 16.8302,
        longitude: 75.7100,
        isUNESCO: false,
        timePeriod: "17th Century (1656)",
        visitorGuidelines: "Open daily. Climb to whispering gallery for acoustic experience. Photography allowed. Best visited in morning. Museum inside showcases Adil Shahi artifacts.",
        folkTales: "Legend says the architect was executed after completion so he couldn't build a similar structure elsewhere. The whispering gallery is said to carry even the softest whisper across the dome.",
        culturalHeritage: "The monument showcases Indo-Islamic architecture with Persian influences. The dome is unsupported by pillars, a remarkable engineering feat. The structure represents the Deccan Sultanate's architectural prowess.",
        cuisine: "Bijapur offers Jolada Rotti, Enne Badanekai (stuffed brinjal), Mutton Pulao, and traditional North Karnataka cuisine with unique spice blends.",
        stories: "The dome spans 44 meters in diameter and is 51 meters high. The whispering gallery creates unique acoustics. The structure has four minarets at corners. It took 30 years to complete.",
        community: "Local guides share stories of the Adil Shahi dynasty. The community celebrates Urs festivals at nearby Sufi shrines. Traditional musicians perform qawwalis.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Rani ki Vav",
        description: "Intricately constructed stepwell featuring seven levels of stairs with over 500 principal sculptures and 1,000 minor sculptures, representing the zenith of stepwell architecture.",
        historicalSignificance: "Built in 1063 by Queen Udayamati in memory of her husband King Bhimdev I. It was submerged in silt for centuries and rediscovered in the 1980s, revealing its magnificent sculptures.",
        category: "monument" as const,
        state: "Gujarat",
        city: "Patan",
        latitude: 23.8589,
        longitude: 72.1019,
        isUNESCO: true,
        timePeriod: "11th Century (1063)",
        visitorGuidelines: "Open daily. Best visited in morning light. Photography allowed. Wear comfortable shoes for stairs. Guided tours available explaining sculptures.",
        folkTales: "Legend says the queen built this stepwell in grief after her husband's death. The sculptures are said to depict the journey from earth to heaven. Hidden chambers are believed to contain treasures.",
        culturalHeritage: "The stepwell showcases Maru-Gurjara architecture with intricate carvings of deities, celestial beings, and mythological scenes. It represents the importance of water conservation in ancient India.",
        cuisine: "Patan offers Gujarati thali, Dhokla, Khandvi, Fafda-Jalebi, and traditional Patola silk weaving demonstrations with local snacks.",
        stories: "The stepwell is 64 meters long, 20 meters wide, and 27 meters deep. It has seven levels with 800 elaborate sculptures. The structure was buried under silt for 700 years. It's designed as an inverted temple.",
        community: "Local communities include descendants of ancient craftsmen. Patan is famous for Patola silk weaving, a tradition passed through generations. The community celebrates Navratri with traditional Garba.",
        view360Url: "https://artsandculture.google.com/story/rani-ki-vav/",
        view3dUrl: "https://artsandculture.google.com/asset/rani-ki-vav/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Fatehpur Sikri",
        description: "Abandoned Mughal city built by Akbar, featuring stunning red sandstone architecture including Buland Darwaza, Jama Masjid, and Panch Mahal.",
        historicalSignificance: "Built between 1571-1585 by Emperor Akbar as his capital. Abandoned after just 14 years due to water scarcity. It represents the pinnacle of Mughal architectural achievement.",
        category: "monument" as const,
        state: "Uttar Pradesh",
        city: "Fatehpur Sikri",
        latitude: 27.0945,
        longitude: 77.6661,
        isUNESCO: true,
        timePeriod: "16th Century (1571-1585)",
        visitorGuidelines: "Open daily except Fridays. Wear comfortable shoes. Carry water. Photography allowed. Hire guide for historical context. Best visited in morning or evening.",
        folkTales: "Legend says Akbar built the city after Sufi saint Salim Chishti predicted the birth of his son. The city was abandoned due to a curse or water shortage, depending on the tale.",
        culturalHeritage: "The city showcases synthesis of Hindu, Islamic, and Persian architecture. The Buland Darwaza is the highest gateway in the world. Panch Mahal represents Persian architectural influence.",
        cuisine: "Nearby Agra offers Mughlai cuisine, Petha, Bedai, Dalmoth, and traditional North Indian dishes. Local dhabas serve authentic meals.",
        stories: "The Buland Darwaza is 54 meters high, built to commemorate Akbar's Gujarat victory. The city has Diwan-i-Khas with a unique central pillar. Akbar's palace had separate quarters for his Hindu and Muslim wives.",
        community: "Local communities include descendants of Mughal-era craftsmen. The area around Salim Chishti's tomb is maintained by Sufi devotees. Traditional marble inlay work continues.",
        view360Url: "https://artsandculture.google.com/story/fatehpur-sikri/",
        view3dUrl: "https://artsandculture.google.com/asset/fatehpur-sikri/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Nalanda University Ruins",
        description: "Ancient Buddhist university ruins, once the world's first residential university attracting scholars from across Asia, featuring monasteries, temples, and lecture halls.",
        historicalSignificance: "Founded in 5th century CE, it flourished until 12th century when destroyed by invaders. At its peak, it housed 10,000 students and 2,000 teachers, with a library of 9 million manuscripts.",
        category: "archaeological" as const,
        state: "Bihar",
        city: "Nalanda",
        latitude: 25.1358,
        longitude: 85.4442,
        isUNESCO: true,
        timePeriod: "5th-12th Century CE",
        visitorGuidelines: "Open daily. Museum nearby displays artifacts. Photography allowed. Wear comfortable shoes. Best visited in morning. Peaceful environment for reflection.",
        folkTales: "Legend says the library burned for three months when destroyed. Stories tell of scholars debating for days. The university is said to have had a rigorous entrance exam with only 30% passing.",
        culturalHeritage: "Nalanda was a center of Buddhist learning, philosophy, medicine, and mathematics. Scholars like Aryabhata and Xuanzang studied here. It represents ancient India's educational excellence.",
        cuisine: "Local Bihar cuisine includes Litti Chokha, Sattu Paratha, Khaja, Thekua, and traditional vegetarian meals. Nearby Rajgir offers Buddhist vegetarian cuisine.",
        stories: "The university had a 9-story library called Dharmaganja. It taught subjects from theology to astronomy. The complex covers 14 hectares with 11 monasteries and 6 temples. It was destroyed by Bakhtiyar Khilji in 1193.",
        community: "Buddhist scholars and archaeologists visit for research. Local communities maintain the site. A new Nalanda University was established nearby in 2014, reviving the ancient tradition.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Elephanta Caves",
        description: "Rock-cut cave temples on Elephanta Island featuring magnificent sculptures of Hindu deities, especially the iconic Trimurti (three-faced Shiva) carved from solid rock.",
        historicalSignificance: "Created between 5th-8th century CE, the caves showcase Hindu art and architecture. The main cave is dedicated to Lord Shiva and contains some of the finest rock-cut sculptures in India.",
        category: "archaeological" as const,
        state: "Maharashtra",
        city: "Mumbai",
        latitude: 18.9633,
        longitude: 72.9315,
        isUNESCO: true,
        timePeriod: "5th-8th Century CE",
        visitorGuidelines: "Accessible by ferry from Gateway of India. Closed on Mondays. Climb 120 steps to caves. Photography allowed. Carry water. Best visited in morning.",
        folkTales: "Legend says the caves were carved by Pandavas in one night. The island got its name from a large elephant sculpture found by Portuguese. Local tales speak of hidden chambers with treasures.",
        culturalHeritage: "The caves showcase Shaivism with intricate sculptures depicting Shiva's various forms. The 6-meter tall Trimurti is a masterpiece. The site hosts Elephanta Festival celebrating classical music and dance.",
        cuisine: "Mumbai offers diverse cuisine including Vada Pav, Pav Bhaji, Bhel Puri, Bombay Duck, and seafood. Ferry ride vendors sell local snacks.",
        stories: "The main cave is 39 meters deep. The Trimurti represents Shiva as creator, preserver, and destroyer. Portuguese soldiers used sculptures for target practice, causing damage. The caves were originally painted in bright colors.",
        community: "Local fishing communities live on the island. Guides share stories passed through generations. The community celebrates Mahashivratri with special fervor. Mumbai's art community organizes cultural events.",
        view360Url: "https://artsandculture.google.com/story/elephanta-caves/",
        view3dUrl: "https://artsandculture.google.com/asset/elephanta-caves-trimurti/",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Chittorgarh Fort",
        description: "Massive hilltop fort, the largest in India, featuring palaces, temples, towers, and reservoirs, symbolizing Rajput valor and sacrifice.",
        historicalSignificance: "Built in 7th century, expanded over centuries. The fort witnessed three major sieges and mass jauhar (self-immolation) by Rajput women. It represents Rajput pride and resistance.",
        category: "fort" as const,
        state: "Rajasthan",
        city: "Chittorgarh",
        latitude: 24.8829,
        longitude: 74.6230,
        isUNESCO: true,
        timePeriod: "7th Century onwards",
        visitorGuidelines: "Open daily. Large complex requires full day. Hire vehicle or guide. Photography allowed. Visit Vijay Stambh and Kirti Stambh. Carry water and snacks.",
        folkTales: "Legend of Rani Padmini's beauty causing Alauddin Khilji's invasion. Stories of mass jauhar by 13,000 women. Tales of Meera Bai's devotion to Krishna and surviving poison attempts.",
        culturalHeritage: "The fort showcases Rajput architecture with 7 gates, each with its own legend. Vijay Stambh (Victory Tower) is 37 meters tall. The fort hosts annual Jauhar Mela commemorating Rajput sacrifice.",
        cuisine: "Chittorgarh offers Dal Baati Churma, Gatte ki Sabzi, Ker Sangri, Laal Maas, and traditional Rajasthani thali with local specialties.",
        stories: "The fort covers 700 acres on a 180-meter high hill. It has 84 water bodies, 4 palaces, and 19 temples. The fort was sacked three times, each followed by jauhar. Rana Kumbha built the Victory Tower.",
        community: "Local communities include descendants of Rajput warriors. Traditional folk musicians perform ballads of valor. The community celebrates Jauhar Mela and Meera Mahotsav annually.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Sundarbans National Park",
        description: "Largest mangrove forest and delta in the world, home to the Royal Bengal Tiger, featuring unique ecosystem of rivers, islands, and diverse wildlife.",
        historicalSignificance: "The Sundarbans has been inhabited for centuries with a rich history of honey collectors, fishermen, and woodcutters. It became a wildlife sanctuary in 1977 and national park in 1984.",
        category: "natural" as const,
        state: "West Bengal",
        city: "Sundarbans",
        latitude: 21.9497,
        longitude: 89.1833,
        isUNESCO: true,
        timePeriod: "Ancient (Protected since 1977)",
        visitorGuidelines: "Best visited November-February. Boat safaris only. Permits required. Stay in eco-tourism lodges. Respect wildlife. No plastic allowed. Hire experienced guides.",
        folkTales: "Legend of Bonbibi, the forest goddess who protects people from tigers. Stories of Dakshin Ray, the tiger god. Tales of shape-shifting tigers and forest spirits protecting the mangroves.",
        culturalHeritage: "The Sundarbans is home to unique traditions of honey collectors (Mawalis) who worship Bonbibi before entering forests. The community celebrates Bonbibi Puja and has rich folk music traditions.",
        cuisine: "Local cuisine includes fresh fish curry, prawn malai curry, crab dishes, and traditional Bengali sweets. Honey from Sundarbans is famous for its unique flavor.",
        stories: "The Sundarbans covers 10,000 sq km with 102 islands. It's home to 400+ Royal Bengal Tigers. The name means 'beautiful forest' in Bengali. The mangroves protect against cyclones and tsunamis.",
        community: "Local communities include fishermen, honey collectors, and forest dwellers. They have unique relationship with tigers, worshipping them while fearing them. Traditional boat-making and fishing techniques passed through generations.",
        viewCount: 0,
        isPublished: true,
      },
      {
        name: "Jantar Mantar",
        description: "Astronomical observatory featuring collection of nineteen architectural astronomical instruments, built by Maharaja Jai Singh II for measuring time and celestial positions.",
        historicalSignificance: "Built in 1734, it's the largest of five observatories built by Jai Singh II. The instruments are still functional and represent the scientific achievements of 18th century India.",
        category: "monument" as const,
        state: "Rajasthan",
        city: "Jaipur",
        latitude: 26.9247,
        longitude: 75.8249,
        isUNESCO: true,
        timePeriod: "18th Century (1734)",
        visitorGuidelines: "Open daily. Hire guide for understanding instruments. Photography allowed. Best visited in morning. Adjacent to City Palace. Allow 1-2 hours.",
        folkTales: "Legend says Jai Singh II was obsessed with astronomy after predicting an eclipse. Stories tell of the instruments being so accurate they could predict monsoons and planetary positions.",
        culturalHeritage: "The observatory represents India's scientific heritage. The Samrat Yantra (sundial) is the world's largest. The site showcases blend of astronomy, architecture, and mathematics.",
        cuisine: "Jaipur offers Dal Baati Churma, Ghewar, Pyaaz Kachori, Laal Maas, and traditional Rajasthani thali. Nearby MI Road has famous sweet shops.",
        stories: "The Samrat Yantra is 27 meters tall and can tell time to 2-second accuracy. The observatory has 19 instruments measuring celestial positions. Jai Singh built five such observatories across India.",
        community: "Local astronomers and scientists study the instruments. The community celebrates science festivals. Traditional astrologers still use the observatory for calculations.",
        view360Url: "https://artsandculture.google.com/story/jantar-mantar-jaipur/",
        view3dUrl: "https://artsandculture.google.com/asset/jantar-mantar/",
        viewCount: 0,
        isPublished: true,
      },
    ];

    for (const site of sites) {
      await ctx.db.insert("heritageSites", {
        ...site,
        createdBy: userId,
      });
    }

    return { success: true, count: sites.length };
  },
});

export const updateExistingSitesWithUrls = mutation({
  args: {},
  handler: async (ctx) => {
    const sites = await ctx.db.query("heritageSites").collect();
    
    const urlMappings: Record<string, { view360Url?: string; view3dUrl?: string }> = {
      "Hampi": {
        view360Url: "https://artsandculture.google.com/story/hampi-monuments/",
        view3dUrl: "https://artsandculture.google.com/asset/vitthala-temple-hampi/"
      },
      "Khajuraho Temples": {
        view360Url: "https://artsandculture.google.com/story/khajuraho-temples/",
        view3dUrl: "https://artsandculture.google.com/asset/kandariya-mahadeva-temple/"
      },
      "Konark Sun Temple": {
        view360Url: "https://artsandculture.google.com/story/sun-temple-konark/",
        view3dUrl: "https://artsandculture.google.com/asset/sun-temple-konark/"
      },
      "Ajanta Caves": {
        view360Url: "https://artsandculture.google.com/story/ajanta-caves/",
        view3dUrl: "https://artsandculture.google.com/asset/ajanta-caves/"
      },
      "Mysore Palace": {
        view360Url: "https://artsandculture.google.com/story/mysore-palace/",
        view3dUrl: "https://artsandculture.google.com/asset/mysore-palace/"
      },
      "Qutub Minar": {
        view360Url: "https://artsandculture.google.com/story/qutub-minar/",
        view3dUrl: "https://sketchfab.com/3d-models/qutub-minar-delhi-india/"
      },
      "Amer Fort": {
        view360Url: "https://artsandculture.google.com/story/amer-fort/",
        view3dUrl: "https://artsandculture.google.com/asset/amer-fort/"
      },
      "Red Fort": {
        view360Url: "https://artsandculture.google.com/story/red-fort-delhi/",
        view3dUrl: "https://artsandculture.google.com/asset/red-fort/"
      },
      "Rani ki Vav": {
        view360Url: "https://artsandculture.google.com/story/rani-ki-vav/",
        view3dUrl: "https://artsandculture.google.com/asset/rani-ki-vav/"
      },
      "Fatehpur Sikri": {
        view360Url: "https://artsandculture.google.com/story/fatehpur-sikri/",
        view3dUrl: "https://artsandculture.google.com/asset/fatehpur-sikri/"
      },
      "Elephanta Caves": {
        view360Url: "https://artsandculture.google.com/story/elephanta-caves/",
        view3dUrl: "https://artsandculture.google.com/asset/elephanta-caves-trimurti/"
      },
      "Jantar Mantar": {
        view360Url: "https://artsandculture.google.com/story/jantar-mantar-jaipur/",
        view3dUrl: "https://artsandculture.google.com/asset/jantar-mantar/"
      }
    };

    let updatedCount = 0;
    
    for (const site of sites) {
      const urls = urlMappings[site.name];
      if (urls) {
        await ctx.db.patch(site._id, urls);
        updatedCount++;
      }
    }

    return { success: true, updatedCount };
  },
});